### ISSUE TITLE
PYJAC_NSP error

### ISSUE THREAD

**Issue by drhcelik** [Aalto-CFD/DLBFoam#14]
Hello,

I keep getting this error for a new mechanism file. I want to use the FFCM-1 mechanism and for that, I compiled everything using the ct2foam utility. I even compiled DLBFoam from scratch but it keeps saying that `/lib/libchemistryModel_DLB.so: undefined symbol: PYJAC_NSP`. How can I solve this problem? `chem.foam` and `therm.foam` in the foam_mech_files folder are also correct.

Thanks.

**Comment by blttkgl** [comment]
Please check your chem_utils.h and chem_utils.c files in your pyJac build. ct2foam should generate two functions called PYJAC_NSP and PYJAC_FWD_RATES, that returns the number of species and reactions. If these functions are not there and you are absolutely sure that you are using ct2foam and not building the pyJac library yourself, the problem lies with the ct2foam, not DLBFoam.

**Comment by drhcelik** [comment]
I found the problem. chem.foam should be in the format of 

```
species
37
(
```

but somehow what I got from ct2foam was something like

```
species
(
```
So, that's why DLBFoam complains about it. I don't know if this was somehow my mistake or not. Anyway, I close this issue. 

Thanks!

**Comment by blttkgl** [comment]
Can you generate the mechanism once again using ct2foam and confirm that this is an issue with the mechanism generation process? If so we should address this.

**Comment by kahilah** [comment]
I believe you have not run "pyjac2foam" command, because that will, or at least should rewrite the species list size accordingly. I'd like to believe you have used ct2foam only and that provides (as desired) only thermodynamic entries because nothing in the mechanism is changed (in contrast to pyjac2foam).

Could you read ct2foam README through and if still problems appear, make a issue there and I'll give it a look.

**Comment by drhcelik** [comment]
@kahilah I got your point. Actually I have used both commands but probably, you are right; I mixed up the output files during OF runtime.

**Comment by srinu010896** [comment]
Hello,

I am getting error while compiling the DLBFoam

g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam8/src/thermophysicalModels/reactionThermo/lnInclude -I/opt/openfoam8/src/thermophysicalModels/basic/lnInclude -I/opt/openfoam8/src/thermophysicalModels/specie/lnInclude -I/opt/openfoam8/src/thermophysicalModels/functions/Polynomial -I/opt/openfoam8/src/ODE/lnInclude -I/opt/openfoam8/src/finiteVolume/lnInclude -I/opt/openfoam8/src/meshTools/lnInclude -I/opt/openfoam8/src/thermophysicalModels/chemistryModel/lnInclude -I../../src/thermophysicalModels/lnInclude -I../../src/thermophysicalModels/chemistryModel/lnInclude -I../../src/thermophysicalModels/chemistryModel/pyJacInclude -DDEBUG -IlnInclude -I. -I/opt/openfoam8/src/OpenFOAM/lnInclude -I/opt/openfoam8/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/test.o Make/linux64GccDPInt32Opt/helpers.o Make/linux64GccDPInt32Opt/testAlgorithms.o Make/linux64GccDPInt32Opt/testChemistryLoad.o Make/linux64GccDPInt32Opt/testLoadBalancerBase.o Make/linux64GccDPInt32Opt/testLoadBalancer.o -L/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib \
    -L/home/skd/OpenFOAM/root-8/platforms/linux64GccDPInt32Opt/lib -lfluidThermophysicalModels -lreactionThermophysicalModels -lspecie -lODE -lfiniteVolume -lmeshTools -lchemistryModel -lchemistryModel_DLB -L/home/skd/OpenFOAM/root-8/platforms/linux64GccDPInt32Opt/lib/unittests/pyjacTestMech/build -lc_pyjac_test -lOpenFOAM -ldl  \
     -lm -o ./test.bin
/usr/bin/ld.bfd: cannot find -lc_pyjac_test
collect2: error: ld returned 1 exit status
/opt/openfoam8/wmake/makefiles/general:140: recipe for target 'test.bin' failed
make: *** [test.bin] Error 1


please help me......

Thank you
![Screenshot from 2022-03-07 18-08-09](https://user-images.githubusercontent.com/94885993/157044786-bf84d5a5-c34f-466f-9dc4-6898697aba7f.png)

**Comment by moreff** [comment]
Hello @srinu010896 ,

It seems that the test chemical mechanism did not compile.
Could you please attach the full log as a file?

**Comment by srinu010896** [comment]
I am attaching file herewith please find the attachment....

Thank you
[Terminal.odt](https://github.com/Aalto-CFD/DLBFoam/files/8202714/Terminal.odt)

**Comment by moreff** [comment]
```
 The C compiler identification is GNU 5.4.0
CMake Error at /usr/share/cmake-3.5/Modules/CMakeDetermineCXXCompiler.cmake:56 (message):
  Could not find compiler set in environment variable CXX:

  /usr/bin/gcc-3.3.

Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

It can't find a C++ compiler in your system. Please install/update it. If you have Ubuntu, run
```
sudo apt update
sudo apt install build-essential
```

**Comment by srinu010896** [comment]
Hai,
Good Morning.
I have updated C++ compiler and when i am again trying to compile the DLBFoam solver i am getting error as 

/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/openmpi-system/libPstream.so: undefined reference to `ompi_mpi_comm_null'
collect2: error: ld returned 1 exit status
/opt/openfoam8/wmake/makefiles/general:140: recipe for target 'test.bin' failed
make: *** [test.bin] Error 1

I am attaching here with log file for your reference 
[Terminal.odt](https://github.com/Aalto-CFD/DLBFoam/files/8220206/Terminal.odt)


please help me
thank you

**Comment by srinu010896** [comment]
Please help me in this.........

I have updated C++ compiler and when i am again trying to compile the DLBFoam solver i am getting error as

/opt/openfoam8/platforms/linux64GccDPInt32Opt/lib/openmpi-system/libPstream.so: undefined reference to `ompi_mpi_comm_null'
collect2: error: ld returned 1 exit status
/opt/openfoam8/wmake/makefiles/general:140: recipe for target 'test.bin' failed
make: *** [test.bin] Error 1


Thank you

**Comment by moreff** [comment]
Hi @srinu010896 , to me it looks like a problem with your OpenFOAM and/or MPI installation.
Check out e.g. [this thread](https://www.cfd-online.com/Forums/openfoam-installation/197390-openfoam-5-source-pack-installation-ubuntu-16-04-a.html).

**Comment by srinu010896** [comment]
Thanks a lot @ moreff, I have followed all your given suggestions

I was used before OpenFOAM8 in UBUNTU 16.04 for the DLBFoam compilation and found that MPI is not supporting with UBUNTU 16.04. 
So, I have changed to UBUNTU 20.01LTS. 
While I am compiling the DLBFoam now I am getting another error. 

Could you please help me in this
I am attaching herewith log file for your reference 

    -lchemistryModel -lfiniteVolume -lmeshTools -L/root/OpenFOAM/root-8/platforms/linux64GccDPInt32Opt/lib/unittests/pyjacTestMech/build -lc_pyjac_test -lOpenFOAM -ldl  \
     -lm -o ./PSRTest.bin
[mpiexec@skd] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:91): unrecognized argument oversubscribe
[mpiexec@skd] HYD_arg_parse_array (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:128): argument matching returned error
[mpiexec@skd] mpiexec_get_parameters (../../../../../src/pm/i_hydra/mpiexec/mpiexec_params.c:1359): error parsing input array
[mpiexec@skd] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1784): error parsing parameters
[mpiexec@skd] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:91): unrecognized argument oversubscribe
[mpiexec@skd] HYD_arg_parse_array (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:128): argument matching returned error
[mpiexec@skd] mpiexec_get_parameters (../../../../../src/pm/i_hydra/mpiexec/mpiexec_params.c:1359): error parsing input array
[mpiexec@skd] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1784): error parsing parameters
[mpiexec@skd] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:91): unrecognized argument oversubscribe
[mpiexec@skd] HYD_arg_parse_array (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:128): argument matching returned error
[mpiexec@skd] mpiexec_get_parameters (../../../../../src/pm/i_hydra/mpiexec/mpiexec_params.c:1359): error parsing input array
[mpiexec@skd] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1784): error parsing parameters


Thank you

[Terminal.odt](https://github.com/Aalto-CFD/DLBFoam/files/8286210/Terminal.odt)

**Comment by moreff** [comment]
Hi @srinu010896 , once again it seems like a problem with your MPI installation.
Check out this discussion: https://stackoverflow.com/a/33784179
Probably you have installed multiple MPI implementations to your system and there is a conflict between them.
You don't need to install MPI separately to your Ubuntu machine, it is present there by default.

**Comment by srinu010896** [comment]
Hai @moreff, Thanks a lot for your reply 

Yeah, MPI is there in the system but while compiling I am getting the error: Error: MKL_ROOT= not found.

How to set this MKL_ROOT could you please help me 

I have tried in many ways but not working it properly

I am attaching herewith log file of the MPI details 

[Terminal.odt](https://github.com/Aalto-CFD/DLBFoam/files/8302030/Terminal.odt)

Thank you

**Comment by moreff** [comment]
Hi @srinu010896 , it is a matter of installing MKL library, not DLBFoam. You can refer to its documentation. 
Or alternatively, you can try the "standalone" option. Please refer to the readme of DLBFoam

**Comment by srinu010896** [comment]
Hai @moreff , Thank you so much....

I have used standalone option and it was compiled and also tested with the given tutorial.

When I am implementing with turbulence flow in reactingFoam I am getting error while using the command: 
skd@skd:~/OpenFOAM/skd-8/run/asian$ mpirun -np $N_PROCS reactingFoam -parallel > log.reactingFoam
----------------------------------------------------------------------------
Open MPI has detected that a parameter given to a command line
option does not match the expected format:

  Option: np
  Param:  reactingFoam

This is frequently caused by omitting to provide the parameter
to an option that requires one. Please check the command line and try again.
----------------------------------------------------------------------------
could you please tell me the exat command line 

I have also tried with commands but it is not working even load balancing working with the given tutorial problem

Thank you

**Comment by kahilah** [comment]
Hi, sounds like your shell variable $N_PROCS is not set --> $N_PROCS returns empty --> "reactingFoam" becomes the -np input argument, which is naturally just wrong. Ensure you have the number of cores set there properly.

**Comment by srinu010896** [comment]
> Hi, sounds like your shell variable $N_PROCS is not set --> $N_PROCS returns empty --> "reactingFoam" becomes the -np input argument, which is naturally just wrong. Ensure you have the number of cores set there properly.

Thank you @kahilah for your response, 
But while running the given tutorial load balancing happening with the same command.

**Comment by kahilah** [comment]
The tutorials set NPROC explicitly. You need to set it yourself in your own applications. Or did I understand something wrong?

**Comment by srinu010896** [comment]
> The tutorials set NPROC explicitly. You need to set it yourself in your own applications. Or did I understand something wrong?

Actually I am very new to Linux as well as OpenFoam.I think you're correct. But I am not able to set it up. My pc having 8 core proc. 
If you could tell me or suggest some material I am grateful to you.  

Thank you

**Comment by srinu010896** [comment]
Hai, 
I have followed the commands given in the Allrun and just changed the geometry but still I am still getting the same error.
/////////////////////////////////////////////
cd pyJac/lib
./runCmake.sh
cd -
cp -r pyJac/foam constant/
cp pyJac/lib/build/libc_pyjac.so constant/foam/

blockMesh
N_PROCS=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
[ -z "$N_PROCS" ] && N_PROCS=4 # if N_PROCS not found, set it to 4
sed -i "s/numberOfSubdomains .*/numberOfSubdomains $N_PROCS;/g" system/decomposeParDict

rm -rf 0
cp -r 0.orig 0

decomposePar -force > log.decompose
mpirun -np $N_PROCS reactingFoam -parallel > log.reactingFoam
/////////////////////////////////////////////////////////////////////////////////////////
please guide me in this

skd@skd:~/OpenFOAM/skd-8/run/101112$ mpirun -np $N_PROCS reactingFoam -parallel > log.reactingFoam
----------------------------------------------------------------------------
Open MPI has detected that a parameter given to a command line
option does not match the expected format:

  Option: np
  Param:  reactingFoam

This is frequently caused by omitting to provide the parameter
to an option that requires one. Please check the command line and try again.
----------------------------------------------------------------------------
Thank you

**Comment by moreff** [comment]
Hi, this question concerns Linux and OpenFOAM basics, not DLBFoam.
The answer is given in the error message and in the kahilah reply: you need to provide the number of cores to the "-np" option

**Comment by srinu010896** [comment]
Thank you everyone for your speedy kind replies.......

I am able to run the solver properly for my required problem

Thank you again......
