### ISSUE TITLE
Sanity check in seulex_LAPACK class methods raise warnings on built-in tutorials

### ISSUE THREAD

**Issue by mahgadalla** [Aalto-CFD/DLBFoam#23]
Before describing the issue, I have to mention this could be just related to stock OpenFOAM case setups, and not DLBFoam!!!

So, in [this link](https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF9/src/ODE_DLB/ODESolvers/seulex_LAPACK/seulex_LAPACK.C#L187) there is a sanity check to ensure temperature values, computed in the solve vector, keep within the prescribed limits of NASA polynomials. So far, this is just additional check which is good.

On another note, in the standard ODE implementation of SEULEX, there's no sanity check for temperature, which is also understandable as the class is derived from a generic ODE library that should operate on any solve vector for stiff ODEs and not necessarily be containing temperature. Therefore, avoiding this sanity check in standard class is also understandable, from the code design perspective.

Now, the problem comes when trying to use DLBFoam on built-in tutorials, particularly the counterFlowFlame2D_GRI. There, warnings are raised as temperature goes off the temperature bounds of NASA polynoms. This can be quite misleading that the problem is in DLBFoam (which it is NOT) as being the one generating warnings in the application log, while standard model works as a charm!

Here, I am not sure whether the problem is just the configuration/BC of the counterFlowFlame2D_GRI (because @moreff has also witnessed similar problems on other tutorials) or this could be in standard implementation of SEULEX? Should that sanity check be completely removed, and we just acknowledge SEULEX implementation as it is in stock OpenFOAM, to avoid misleading interpretation of those warnings?

**Comment by kahilah** [comment]
So a bit of implementation history...I added that if-clause there in the very beginning while working with OF-2.4.x without any pyjac or any other add-ons. Including such a check was motivated by the fact that at that time OpenFoam was easily overshooting the temperature due to poor evaluation of the reaction rates and especially if your case was not well posed. I wanted to force the ODE solver to reduce it's internal time step in such cases to ensure more robust performance.

> "So far, this is just additional check which is good."
- Note that it's not just "a check", but within that if() I forced the seul() function to return false, meaning that the seulex algorithm starts ramp order up and internal time step down, to ensure robust convergence of the implicit algorithm. That is kind of the idea of the stability check I refer to in the original Hairer's implementation.

The best example when you often overshoot NASA limits is that you start a transient simulation with poor initial guess, so on the first time steps your PIMPLE loop takes several iterations to converge. During the first PIMPLE steps the energy equation may result in poor convergence and hence high/low temperature values in certain cells. Of course we can limit the temperature values on flow side by using limiters but the thing is that if your input to ODE is already close to NASA limits, then your ODE solver may result in divergence if the NASA polynomial are not smooth near the min/max limits.

Next question is that how often such occasion happens and whether this check is really needed? Most chemical mechanisms have well designed thermo data so NASA polynomials are very smooth near the min/max limits, meaning that even you greatly go over the limits, it won't lead to problems. However, especially in heavily reduced few step mechanisms I have seen polynomials which start to skyrocket quickly near the limits. In such cases this check really helps.

Long time ago I made a test in which I artificially modified GRI thermo data to make it unstable in tutorials. With this check, the simulations were stable. 

All in all, is this check really required? - not necessarily, but it's a great sign for a user that you can most probably design the case setup better because for a moment you really are on the verge of divergence, depending on the thermo data behaviour. What you could do is to remove the print and keep the if-clause so you still affect the ODE performance without telling it to the user. But I'd prefer to know that I'm off the NASA limits IN the ODE.

**Comment by moreff** [comment]
I think there might be a misunderstanding of the issue. This warning prints unphysical values of temperatures. For example, this is what I get on one of the iterations with counterFlowFlame2D_GRI:

```
Warning: You exceeded the NASA temperature limits: T=5162.07
Warning: You exceeded the NASA temperature limits: T=10179
Warning: You exceeded the NASA temperature limits: T=-4162.5
Warning: You exceeded the NASA temperature limits: T=28717.1
Warning: You exceeded the NASA temperature limits: T=-197.203
Warning: You exceeded the NASA temperature limits: T=-7510.06
Warning: You exceeded the NASA temperature limits: T=183.553
```

It seems that ODE solver is simply diverging in some cells with a given integration time step and corresponding problem stiffness. As you mentioned, this is not just a check, it forces `seul()` to return false, which in turn will result in a reduction of an integration time step until eventually the solution will be anyway found with a given accuracy.

I think this warning of course can be an indication that the CFD time step the user chose may be too large for ODE integrator and thus probably too large also for assumptions behind chemistry operator-splitting if one is running a transient case. But for a steady-state problem, this can be part of a normal opeartion.

I would keep the check itself (it speeds up convergence under this kind of conditions), but I would remove the warning message. Or at least reformulate it. In the current form ("You exceeded temperature limits") it will probably urge the user to go to paraview to look for some cells with these temperatures and of course not find any.

**Comment by moreff** [comment]
It is also interesting to note that in this particular case (counterFlowFlame2D_GRI), these warnings trigger at cell temperatures around 1850-1900K and after some simulation time (not right after the start). 
I decreased the time step twice from ~0.37ms and it removed warnings.

So if we keep the warning message, I would ideally:
1. Remove the ODE solver's temperature value from it, since it does nothing but confuses.
2. Note that the chemistry problem might be too stiff.
3. Maybe mention possible reasons: too large time step, poor polynomial data...
4. Maybe additionally indicate that this is not a critical error, the chemistry problem is solved with a given error tolerance anyway

But in this way, the warning message becomes too long :)
So I would still remove the warning not to confuse the user (but keep the check).
Note that we also have this message printed if the check fails and if the debug switch is on:
https://github.com/Aalto-CFD/DLBFoam/blob/4f9d29a3533d7f450656168aae7dc60993a150e5/src/ODE_DLB/ODESolvers/seulex_LAPACK/seulex_LAPACK.C#L399

**Comment by kahilah** [comment]
You can remove the print if it bothers you, just keep the return. It's rather rare to see that message anyway (outside tutorials :D)

"these warnings trigger at cell temperatures around 1850-1900K and after some simulation time."
- This may be related to adjustable time stepping used in those tutorials?

**Comment by moreff** [comment]
I tried both adjustable and fixed time steps, but these warnings are anyway delayed.

**Comment by blttkgl** [comment]
I agree with all the possible solutions Ilya suggested, and the wording at the moment might make the user go look for an error where there may not be any (at least nothing super critical). As a suggestion, one option could be the print out the warning a number of times. When there is a meshing issue that is not critical to the simulation, CONVERGE CFD prints something like this:

'Warning: XYZ is happening. This is due to ABC. This message will be printed for 20 iterations.'

**Comment by moreff** [comment]
@blttkgl this can be an option. But it would require some synchronization between the master process and others. Also, it still needs to be somehow clearly formulated...

I removed this message for now. If someone wants to see a warning if the chemistry solver diverges, debug switch can be added to the `system/controlDict`:
```
DebugSwitches
{
    seulex_LAPACK 1;
}
```
It will print this message:  
https://github.com/Aalto-CFD/DLBFoam/blob/292ec20082eb07092f974b1d8a322a1b049c51a0/src/ODE_DLB/ODESolvers/seulex_LAPACK/seulex_LAPACK.C#L398

**Comment by mahgadalla** [comment]
Thank you all for the elaboration. I also agree on the current fix to just remove the warning message while keeping it for debug, and to keep the return. At the end, both Standard and ode_pyJac models deliver stable integration for very stiff problems, while the additional stability check considered here could be more useful in avoiding under-/over-shooting possibly at the first few sub-iteratio  steps during single ODE integration.

Perhaps, the additional stability criterion can be somewhere mentioned in the readme. This can also help in the case of deciding to keep the warning (reformulated) to highlight it under FAQ.

**Comment by mahgadalla** [comment]
Thank you, @kahilah and all, for the elaboration. I also agree on the current fix to just remove the warning message while keeping it for debug, and to keep the return. At the end, both Standard and ode_pyJac models deliver stable integration for very stiff problems, while the additional stability check considered here could be more useful in avoiding under-/over-shooting possibly at the first few sub-iteratio  steps during single ODE integration.

Perhaps, the additional stability criterion can be somewhere mentioned in the readme. This can also help in the case of deciding to keep the warning (reformulated) to highlight it under FAQ.
