### ISSUE TITLE
Polynomial type fits of mechanism transport data need to be 7th order

### ISSUE THREAD

**Issue by mahgadalla** [Aalto-CFD/DLBFoam#26]
Apparently the mechanism data IN THE TUTORIALS have been generated for 3rd order polynomial fits, consistently with Cantera and Chemkin. While this is not a problem for Sutherland models, using e.g. logPolynomial models results in OpenFOAM crashes due to that OpenFOAM forces 7th order polynomials. The package [ct2foam/pyjac2foam](https://github.com/kahilah/ct2foam) can be utilized to properly generate the 7th order polynomial type fits of the mechanism transport data.

**Comment by drhcelik** [comment]
Just out of curiosity, is there anything related with this in DLBFoam? I feel like it is ct2foam side issue. I use logPolynomial feature quite a lot and changing ` transport_fits = utils.fit_ct_transport(data, poly_order=3)` in mech2foam-py in ct2foam  to 7 fixes this issue.

**Comment by kahilah** [comment]
I think the only *issue* here is that [here](https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF10_dev/tutorials/reactingFoam/shearlayer_DLB/constant/foam/thermo.foam) shows "muLogCoeffs<4>" defined while OF supports by default "muLogCoeffs<8>". However, in the tutorial one has sutherland model activated so no crash appears.

Note that while OpenFoam expects by default 8 coefficients, it doesn't mean you *must* use 7th order polynomial. Actually, I wouldn't advice that as it may have unwanted consequences.

So by default ct2foam utilises 3rd order polynomial (old standard) but it writes out still 8 coefficients to be compatible with OpenFoam input. The last 4 coefficients are just zero:
muLogCoeffs<8>  (   -22.781168244489972 3.6861969889911728 -0.4030415513216384 0.017817116130884172 0 0 0 0  );

This does not lead to crash.

Now one could do as @drhcelik suggested and change the ct2foam default to fit 7th order polynomial. However, as most transport data has low gradients, the 7th order fit may work very nicely in the typical temperature range but may, potentially, induce high noise at very high/low temperature range depending on your reference data sets (old polynomial vs. experimental data).

For a well behaving simulations this is not an issue, but imagine you're running a steady-state case in which slow convergence may yield high temperature limit values and if your thermodynamic quantities start to oscillate a lot due to a poor fit, convergence is even harder. 

Therefore, I'd argue that ct2foam default behavior is acceptable and shouldn't be changed.

**Comment by blttkgl** [comment]
I do not think this issue belongs here. As @kahilah pointed out, the ct2foam already takes care of this issue by padding zeros and spitting out 8 term entries. Considering the fact that 3rd and 4th order polynomials are pretty much the standard in e.g. Cantera or Chemkin, I agree with his point about issues that may arise from higher order polynomials. In either case this ticket belongs to either advanced tutorials, or ct2foam repository, since @moreff already padded the existing mechanism files with zeros here: https://github.com/Aalto-CFD/DLBFoam/commit/62dadcc9dcbcdc9283dc2155ccff540aef6d128c

**Comment by drhcelik** [comment]
@kahilah I totally agree with your points, I just have got the impression that he wants the fit also should be in 7th order; that's why I suggested that.

**Comment by mahgadalla** [comment]
Thank you @all for the insights. So, it is still recommended to utilize a polynomial of degree 3 type, while appending zeroes just for consistency. Maybe the question should be then elaborated on why OpenFOAM encourages the 7 degree type polynoms!
I will keep the issue open meanwhile, as the tutorials mechanisms are not updated, although those inside utilities dir are updated in the mentioned commit.

**Comment by kahilah** [comment]
I'd imagine that one may require high order polynomial when dealing with non-newtonian transport, high-temperature plasma-like fluids, and I have seen that some oils have almost like adiscontinuity in viscocity at some temperatures.

**Comment by blttkgl** [comment]
Fixed v1.1_OF9: https://github.com/Aalto-CFD/DLBFoam/commit/546f27a05bad1127e959684dfc9402dfa2dff0ac
Fixed in v1.1_OF10 (will be merged soon via active pull request): https://github.com/Aalto-CFD/DLBFoam/commit/b859f471d2241dc61f9fd10d755628966857d086
