### ISSUE TITLE
Changes related to OF-dev

### ISSUE THREAD

**Issue by drhcelik** [Aalto-CFD/DLBFoam#38]
Hey,

Shouldn't be [this](https://github.com/Aalto-CFD/DLBFoam/blob/edc97515aa5d56c863a8700dccd9d600fd794b44/src/thermophysicalModels/chemistryModel/refMapping/mixtureFraction.C#L45) line and two bottom of that something like ```2.0 * dict.lookupOrDefault<label>("C", 0) / thermo.Wi(i).value());```

and [this](https://github.com/Aalto-CFD/DLBFoam/blob/edc97515aa5d56c863a8700dccd9d600fd794b44/tests/validation/pyjacTests/PSRTest/PSRTest.C#L171) something like this:
```bool Hcheck0b = validatePyjacEnthalpy(Y, 298.15, thermo.ha().ref()[0]-thermo.hs().ref()[0], 1e-6);```

At least this was the only way to compile on CSC using latest OF-dev module for me.

**Comment by blttkgl** [comment]
Hey Hasan, yes that is correct.

Regarding the second change, I actually implemented it this way on my end:

        bool Hcheck0b = validatePyjacEnthalpy(Y, 298.15, thermo.ha().ref()[0] - thermo.he()[0], 1e-6);

It is because over here
https://github.com/OpenFOAM/OpenFOAM-10/blob/89f925dc708d068f84f51e8317e3bebcda64f5cb/test/multiphase/multiphaseEulerFoam/thermal/waterEvaporation/system/continuity#L32

tmp<volScalarField> tEa = thermo.he() + thermo.hc();

implementation is later replaced by

 thermo.ha() 

so hc() = ha() - he(), right?

In any case, my pull request https://github.com/Aalto-CFD/DLBFoam/pull/37 implements these changes as well, I am waiting for @arintanen  or @moreff  to check it out and decide if they want to take it in.

**Comment by arintanen** [comment]
Hi Hasan and Bulut,

Bulut, I think it should be implemented according to Hasan (or extend the validation to compare enthalpy of formation of individual species). We are looking here for the difference between absolute and sensible enthalpy to retrieve the chemical enthalpy. thermo.he() returns either sensible internal enthalpy or sensible internal energy depending on the solution variable used in the energy equation and thus the validation fails if the latter is used. 

Regarding the pull request, we try to check it next week.

**Comment by blttkgl** [comment]
Hey Aleksi, your description seems to be correct, and I will make the necessary changes.

Perhaps @kahilah can say a few words about this just to be on the safe side?

**Comment by kahilah** [comment]
Correct, he() has a dependency on the primary energy variable choice.

However, originally, as still nowadays, whenever using pyjac one should stick with sensibleEnthalpy as otherwise one would need to create pyjac files w.r.t. constant CV instead of constant CP and one would need to add a correction to the Qdot function to be precise. I think in some original legacy codes and readme files this was highlighted.

Note that "error" due to using CP instead of CV is not large but error accumulation becomes dependent of the time step.

**Comment by moreff** [comment]
Resolved by 3c1f70231f1b1a798a12345d98c516ae686f9a0e
